language: python
sudo: false
python: 3.3
install:
  - pip install -r requirements.txt
  - ./setup.py install
script:
  - py.test --cov=sublimedsl --cov-report term -vv
  - pep8
after_success:
  - coveralls
